// 语言配置文件
const langs = {
  zh: {
    title: "Easy Soap",
    subtitle: "一个简单、高效的SOAP接口测试工具，支持跨域请求",
    urlLabel: "服务URL:",
    urlPlaceholder: "请输入SOAP服务URL",
    actionLabel: "SOAP Action:",
    actionPlaceholder: "请输入SOAP Action (可选)",
    requestLabel: "SOAP请求体:",
    requestPlaceholder: "请输入SOAP XML请求体",
    sendButton: "发送请求",
    responseTitle: "响应结果",
    statusLabel: "状态:",
    timeLabel: "耗时:",
    waitingMessage: "等待请求...",
    sendingMessage: "发送请求中，请稍候...",
    noResponseData: "无响应数据",
    requestFailed: "请求失败",
    backendError: "无法从后台获取响应，可能是浏览器扩展出现问题",
    corsError: "请求失败，可能是由于跨域问题导致。请查看浏览器控制台获取更多信息。",
    enterUrlAlert: "请输入SOAP服务URL",
    enterBodyAlert: "请输入SOAP请求体",
    footer: "Easy Soap v1.1.0 | 一个简单的跨域SOAP请求测试工具",
    langSwitchLabel: "语言:",
    themeSwitchLabel: "主题:",
    lightTheme: "明亮",
    darkTheme: "深色",
    proTheme: "专业",
    formatBtn: "🔧 格式化",
    clearBtn: "🗑️ 清空",
    copyBtn: "📋 复制",
    copySuccess: "✅ 已复制",
    copyFailed: "❌ 复制失败，请手动复制",
    historyLabel: "历史记录:",
    historyPlaceholder: "-- 选择历史记录 --",
    saveHistoryBtn: "💾 保存",
    clearHistoryBtn: "🗑️ 清空历史",
    saveSuccess: "已保存",
    confirmClearHistory: "确定要清空所有历史记录吗？",
    headersLabel: "自定义 Headers:",
    addHeaderBtn: "➕ 添加",
    promptHistoryName: "请输入历史记录名称（留空则使用默认名称）：",
    confirmBtn: "确认",
    cancelBtn: "取消"
  },
  en: {
    title: "Easy Soap",
    subtitle: "A simple and efficient SOAP API testing tool with cross-origin support",
    urlLabel: "Service URL:",
    urlPlaceholder: "Enter SOAP service URL",
    actionLabel: "SOAP Action:",
    actionPlaceholder: "Enter SOAP Action (optional)",
    requestLabel: "SOAP Request Body:",
    requestPlaceholder: "Enter SOAP XML request body",
    sendButton: "Send Request",
    responseTitle: "Response",
    statusLabel: "Status:",
    timeLabel: "Time:",
    waitingMessage: "Waiting for request...",
    sendingMessage: "Sending request, please wait...",
    noResponseData: "No response data",
    requestFailed: "Request failed",
    backendError: "Could not get response from background script, browser extension may have an issue",
    corsError: "Request failed, possibly due to CORS issues. Check browser console for more information.",
    enterUrlAlert: "Please enter a SOAP service URL",
    enterBodyAlert: "Please enter a SOAP request body",
    footer: "Easy Soap v1.1.0 | A simple cross-origin SOAP request testing tool",
    langSwitchLabel: "Language:",
    themeSwitchLabel: "Theme:",
    lightTheme: "Light",
    darkTheme: "Dark",
    proTheme: "Professional",
    formatBtn: "🔧 Format",
    clearBtn: "🗑️ Clear",
    copyBtn: "📋 Copy",
    copySuccess: "✅ Copied",
    copyFailed: "❌ Copy failed, please copy manually",
    historyLabel: "History:",
    historyPlaceholder: "-- Select History --",
    saveHistoryBtn: "💾 Save",
    clearHistoryBtn: "🗑️ Clear History",
    saveSuccess: "Saved",
    confirmClearHistory: "Are you sure you want to clear all history records?",
    headersLabel: "Custom Headers:",
    addHeaderBtn: "➕ Add",
    promptHistoryName: "Enter a name for this history record (leave blank for default):",
    confirmBtn: "Confirm",
    cancelBtn: "Cancel"
  }
}; 